require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgendamentosController do

  # This should return the minimal set of attributes required to create a valid
  # Agendamento. As you add validations to Agendamento, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "arquivo" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgendamentosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all agendamentos as @agendamentos" do
      agendamento = Agendamento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:agendamentos).should eq([agendamento])
    end
  end

  describe "GET show" do
    it "assigns the requested agendamento as @agendamento" do
      agendamento = Agendamento.create! valid_attributes
      get :show, {:id => agendamento.to_param}, valid_session
      assigns(:agendamento).should eq(agendamento)
    end
  end

  describe "GET new" do
    it "assigns a new agendamento as @agendamento" do
      get :new, {}, valid_session
      assigns(:agendamento).should be_a_new(Agendamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested agendamento as @agendamento" do
      agendamento = Agendamento.create! valid_attributes
      get :edit, {:id => agendamento.to_param}, valid_session
      assigns(:agendamento).should eq(agendamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Agendamento" do
        expect {
          post :create, {:agendamento => valid_attributes}, valid_session
        }.to change(Agendamento, :count).by(1)
      end

      it "assigns a newly created agendamento as @agendamento" do
        post :create, {:agendamento => valid_attributes}, valid_session
        assigns(:agendamento).should be_a(Agendamento)
        assigns(:agendamento).should be_persisted
      end

      it "redirects to the created agendamento" do
        post :create, {:agendamento => valid_attributes}, valid_session
        response.should redirect_to(Agendamento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agendamento as @agendamento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agendamento.any_instance.stub(:save).and_return(false)
        post :create, {:agendamento => { "arquivo" => "invalid value" }}, valid_session
        assigns(:agendamento).should be_a_new(Agendamento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Agendamento.any_instance.stub(:save).and_return(false)
        post :create, {:agendamento => { "arquivo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agendamento" do
        agendamento = Agendamento.create! valid_attributes
        # Assuming there are no other agendamentos in the database, this
        # specifies that the Agendamento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Agendamento.any_instance.should_receive(:update_attributes).with({ "arquivo" => "MyString" })
        put :update, {:id => agendamento.to_param, :agendamento => { "arquivo" => "MyString" }}, valid_session
      end

      it "assigns the requested agendamento as @agendamento" do
        agendamento = Agendamento.create! valid_attributes
        put :update, {:id => agendamento.to_param, :agendamento => valid_attributes}, valid_session
        assigns(:agendamento).should eq(agendamento)
      end

      it "redirects to the agendamento" do
        agendamento = Agendamento.create! valid_attributes
        put :update, {:id => agendamento.to_param, :agendamento => valid_attributes}, valid_session
        response.should redirect_to(agendamento)
      end
    end

    describe "with invalid params" do
      it "assigns the agendamento as @agendamento" do
        agendamento = Agendamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agendamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => agendamento.to_param, :agendamento => { "arquivo" => "invalid value" }}, valid_session
        assigns(:agendamento).should eq(agendamento)
      end

      it "re-renders the 'edit' template" do
        agendamento = Agendamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Agendamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => agendamento.to_param, :agendamento => { "arquivo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agendamento" do
      agendamento = Agendamento.create! valid_attributes
      expect {
        delete :destroy, {:id => agendamento.to_param}, valid_session
      }.to change(Agendamento, :count).by(-1)
    end

    it "redirects to the agendamentos list" do
      agendamento = Agendamento.create! valid_attributes
      delete :destroy, {:id => agendamento.to_param}, valid_session
      response.should redirect_to(agendamentos_url)
    end
  end

end
